version: '2'
services:
  java-demo:
    build: ./java-demo
  node-demo:
    build: ./node-demo
    ports:
    - "3000:3000"
  consul:
    image: consul
    ports:
    - "8500:8500"
    - "8600:8600"
  rabbit:
    image: rabbitmq
    ports:
    - "5672:5672"
