version: '2'
services:
  consul:
    image: consul
    ports:
    - "8500:8500"
  router-nginx:
    build: ./router-nginx
    ports:
    - "8080:8080"
    - "8081:8081"
    environment:
    - RECRUITER_PORT=8080
    - CANDIDATE_PORT=8081
    depends_on:
    - consul
  recruiter-microservice-1:
    build: ./recruiter-microservice
    links:
    - consul
    - router-nginx
    environment:
    - CONSUL_HOST=consul
    - CANDIDATE_URL=http://router-nginx:8081
    - RECRUITER_NAME=Helen
  recruiter-microservice-2:
    build: ./recruiter-microservice
    links:
    - consul
    - router-nginx
    environment:
    - CONSUL_HOST=consul
    - CANDIDATE_URL=http://router-nginx:8081
    - RECRUITER_NAME=Gill
  candidate-microservice-1:
    build: ./candidate-microservice
    links:
    - consul
    environment:
    - SPRING_CLOUD_CONSUL_HOST=consul
    - CANDIDATE_NAME=Amos
  candidate-microservice-2:
    build: ./candidate-microservice
    links:
    - consul
    environment:
    - SPRING_CLOUD_CONSUL_HOST=consul
    - CANDIDATE_NAME=Katarina
