version: '2'
services:
  consul:
    image: consul
    ports:
    - "8500:8500"
    - "8600:8600/udp"
  rabbit:
    image: rabbitmq
    ports:
    - "5672:5672"
  nginx-consul:
    build: ./nginx-consul
    ports:
    - "8085:80"
    depends_on:
    - consul
  ping-nodejs-1:
    build: ./ping-nodejs
    ports:
    - "3006:3006"
    links:
    - consul
    - rabbit
    environment:
    - CONSUL_HOST=consul
    - MSB_BROKER_HOST=rabbit
    - HTTP_PORT=3006
  ping-nodejs-2:
    build: ./ping-nodejs
    ports:
    - "3007:3007"
    links:
    - consul
    - rabbit
    environment:
    - CONSUL_HOST=consul
    - MSB_BROKER_HOST=rabbit
    - HTTP_PORT=3007
  pong-java:
    build: ./pong-java
    links:
    - consul
    - rabbit
    environment:
    - SPRING_CLOUD_CONSUL_HOST=consul
    - MSB_BROKER_HOST=rabbit
