version: '2'
services:
  consul:
    image: consul
    ports:
    - "8500:8500"
  nginx-consul:
    build: ./nginx-consul
    ports:
    - "8080:80"
    - "8081:81"
    depends_on:
    - consul
  string-util-microservice-1:
    build: ./string-util-microservice
    links:
    - consul
    - nginx-consul
    environment:
    - CONSUL_HOST=consul
    - CAPITALIZER_URL=http://nginx-consul
  string-util-microservice-2:
    build: ./string-util-microservice
    links:
    - consul
    - nginx-consul
    environment:
    - CONSUL_HOST=consul
    - CAPITALIZER_URL=http://nginx-consul
  capitalizer-microservice-1:
    build: ./capitalizer-microservice
    links:
    - consul
    environment:
    - SPRING_CLOUD_CONSUL_HOST=consul
  capitalizer-microservice-2:
    build: ./capitalizer-microservice
    links:
    - consul
    environment:
    - SPRING_CLOUD_CONSUL_HOST=consul
