version: '2'
services:
  consul:
    image: consul
    ports:
    - "8500:8500"
  nginx-consul:
    build: ./nginx-consul
    ports:
    - "8080:80"
    - "8081:81"
    depends_on:
    - consul
  recruiter-microservice-1:
    build: ./recruiter-microservice
    links:
    - consul
    - nginx-consul
    environment:
    - CONSUL_HOST=consul
    - CANDIDATE_URL=http://nginx-consul
  recruiter-microservice-2:
    build: ./recruiter-microservice
    links:
    - consul
    - nginx-consul
    environment:
    - CONSUL_HOST=consul
    - CANDIDATE_URL=http://nginx-consul
  candidate-microservice-1:
    build: ./candidate-microservice
    links:
    - consul
    environment:
    - SPRING_CLOUD_CONSUL_HOST=consul
  candidate-microservice-2:
    build: ./candidate-microservice
    links:
    - consul
    environment:
    - SPRING_CLOUD_CONSUL_HOST=consul
